global using Azure.Communication.CallAutomation;
global using Azure.Messaging.EventGrid;
global using Azure.Messaging.EventGrid.SystemEvents;
global using communication_services_recording.Events;
global using communication_services_recording.Interfaces;
global using Microsoft.AspNetCore.Mvc;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using communication_services_recording.Models;
